### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by stasysp** [juliaKirilenko/jML#1]
Year_of_Release - категориальный признак, а выбран, как числовой (деление в [13] не подходит для этих данных почему см https://github.com/SokolovaNastya/MachineLearning/issues/1)
Нужно выбросить признаки с низким feature importance (важно, модель для отбора признаков и для предсказания должны быть разными (например, отбрасывать можно регрессией с l1 регуляризацией)

**Comment by juliaKirilenko** [comment]
Я всё поправила.
